//COMPONENTS
import { Navbar } from "../components/Navbar.jsx";

//FONTS
import { Roboto } from "next/font/google";

//CSS GLOBAL
import "./globals.css";

const roboto = Roboto({
  weight: ["300", "400", "900"],
  styles: ["normal", "italic"],
  subsets: ["latin"],
});

export const metadata = {
  title: 'Proyecto 1',
  description: 'Generated by Next.js',
  keywords: ["tienda" , "online"],
  authors: [{name: "Gonzalo"}],
  creator: "Gonzalo Beristain",
  publisher: "Gonzalo Beristain",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Navbar />

        {children}
      </body>
    </html>
  )
};