export const metadata = {
    title: 'About',
    description: 'Generated by Next.js',
    keywords: ["tienda" , "online"],
    authors: [{name: "Gonzalo"}],
    creator: "Gonzalo Beristain",
    publisher: "Gonzalo Beristain",
};

const aboutUs = () => {
    return (
        <h1 className="text-5xl font-bold py-3 text-center">ABOUT US</h1>
    )
}

export default aboutUs;